import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card, CardContent } from "./ui/card";
import { Button } from "./ui/button";
import { Badge } from "./ui/badge";
import { ChevronRight, Plus } from "lucide-react";
import { useNavigate } from "react-router-dom";
export const HomeSection = ({ title, actions, quickActions, maxItems = 3, layout = "horizontal", emptyState, onActionClick, }) => {
    const navigate = useNavigate();
    const handleActionClick = (action) => {
        if (onActionClick) {
            onActionClick(action);
        }
        navigate(action.cta.to);
    };
    const displayActions = actions.slice(0, maxItems);
    if (actions.length === 0 && emptyState) {
        return (_jsxs("div", { className: "px-4 mb-6", children: [" ", _jsxs("div", { className: "flex items-center justify-between mb-4", children: [" ", _jsx("h2", { children: title }), " ", quickActions && quickActions.length > 0 && (_jsxs("div", { className: "flex gap-2", children: [" ", quickActions.slice(0, 2).map((action, index) => (_jsxs(Button, { size: "sm", variant: "outline", onClick: () => navigate(action.to), className: "h-8", children: [" ", action.icon, " ", action.label, " "] }, index))), " "] })), " "] }), " ", _jsxs(Card, { className: "p-6 text-center", children: [" ", _jsx("h3", { className: "mb-2", children: emptyState.title }), " ", _jsxs("p", { className: "text-sm text-muted-foreground mb-4", children: [" ", emptyState.description, " "] }), " ", emptyState.cta && (_jsxs(Button, { size: "sm", onClick: () => navigate(emptyState.cta.to), children: [" ", _jsx(Plus, { className: "w-4 h-4 mr-2" }), " ", emptyState.cta.label, " "] })), " "] }), " "] }));
    }
    return (_jsxs("div", { className: "px-4 mb-6", children: [" ", _jsxs("div", { className: "flex items-center justify-between mb-4", children: [" ", _jsx("h2", { children: title }), " ", quickActions && quickActions.length > 0 && (_jsxs("div", { className: "flex gap-2", children: [" ", quickActions.map((action, index) => (_jsxs(Button, { size: "sm", variant: "outline", onClick: () => navigate(action.to), className: "h-8", children: [" ", action.icon, " ", action.label, " "] }, index))), " "] })), " "] }), " ", layout === "horizontal" ? (_jsxs("div", { className: "flex gap-3 overflow-x-auto pb-2", children: [" ", displayActions.map((action) => (_jsxs(Card, { className: "flex-shrink-0 w-72 cursor-pointer hover:shadow-md transition-shadow", onClick: () => handleActionClick(action), children: [" ", _jsxs(CardContent, { className: "p-4", children: [" ", _jsxs("div", { className: "flex items-start justify-between mb-3", children: [" ", _jsxs("div", { className: "flex-1", children: [" ", _jsx("h3", { className: "text-sm line-clamp-1", children: action.title }), " ", action.subtitle && (_jsxs("p", { className: "text-xs text-muted-foreground mt-1 line-clamp-1", children: [" ", action.subtitle, " "] })), " "] }), " ", action.badge && (_jsxs(Badge, { variant: "outline", className: "text-xs ml-2", children: [" ", action.badge.text, " "] })), " "] }), " ", _jsxs("div", { className: "flex items-center justify-between", children: [" ", _jsxs(Button, { size: "sm", className: "h-7 text-xs", children: [" ", action.cta.label, " "] }), " ", _jsx(ChevronRight, { className: "w-3 h-3 text-muted-foreground" }), " "] }), " "] }), " "] }, action.id))), " "] })) : (_jsxs("div", { className: "space-y-2", children: [" ", displayActions.map((action) => (_jsxs(Card, { className: "cursor-pointer hover:shadow-md transition-shadow", onClick: () => handleActionClick(action), children: [" ", _jsxs(CardContent, { className: "p-3", children: [" ", _jsxs("div", { className: "flex items-center justify-between", children: [" ", _jsxs("div", { className: "flex-1", children: [" ", _jsx("h3", { className: "text-sm", children: action.title }), " ", action.subtitle && (_jsxs("p", { className: "text-xs text-muted-foreground", children: [" ", action.subtitle, " "] })), " "] }), " ", _jsxs("div", { className: "flex items-center gap-2", children: [" ", action.badge && (_jsxs(Badge, { variant: "outline", className: "text-xs", children: [" ", action.badge.text, " "] })), " ", _jsxs(Button, { size: "sm", variant: "outline", className: "h-6 text-xs", children: [" ", action.cta.label, " "] }), " "] }), " "] }), " "] }), " "] }, action.id))), " "] })), " ", actions.length > maxItems && (_jsxs("div", { className: "mt-3 text-center", children: [" ", _jsxs(Button, { variant: "ghost", size: "sm", onClick: () => navigate(`/${actions[0].domain}`), children: [" ", "View all (", actions.length, ")", " "] }), " "] })), " "] }));
};
